// cmd/fyne-gui/new-core/protocol/signaling.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: signaling.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalingMessage - это обертка для всех сообщений, связанных
// с установкой и управлением P2P медиа-соединениями.
type SignalingMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // Уникальный ID для этого конкретного звонка (генерируется GUI)
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalingMessage_Offer
	//	*SignalingMessage_Answer
	//	*SignalingMessage_Candidate
	//	*SignalingMessage_Hangup
	//	*SignalingMessage_Negotiation
	Payload       isSignalingMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalingMessage) Reset() {
	*x = SignalingMessage{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalingMessage) ProtoMessage() {}

func (x *SignalingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalingMessage.ProtoReflect.Descriptor instead.
func (*SignalingMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalingMessage) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SignalingMessage) GetPayload() isSignalingMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalingMessage) GetOffer() *CallOffer {
	if x != nil {
		if x, ok := x.Payload.(*SignalingMessage_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *SignalingMessage) GetAnswer() *CallAnswer {
	if x != nil {
		if x, ok := x.Payload.(*SignalingMessage_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *SignalingMessage) GetCandidate() *ICECandidate {
	if x != nil {
		if x, ok := x.Payload.(*SignalingMessage_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

func (x *SignalingMessage) GetHangup() *CallHangup {
	if x != nil {
		if x, ok := x.Payload.(*SignalingMessage_Hangup); ok {
			return x.Hangup
		}
	}
	return nil
}

func (x *SignalingMessage) GetNegotiation() *CallNegotiation {
	if x != nil {
		if x, ok := x.Payload.(*SignalingMessage_Negotiation); ok {
			return x.Negotiation
		}
	}
	return nil
}

type isSignalingMessage_Payload interface {
	isSignalingMessage_Payload()
}

type SignalingMessage_Offer struct {
	Offer *CallOffer `protobuf:"bytes,2,opt,name=offer,proto3,oneof"` // Предложение начать звонок
}

type SignalingMessage_Answer struct {
	Answer *CallAnswer `protobuf:"bytes,3,opt,name=answer,proto3,oneof"` // Ответ на предложение
}

type SignalingMessage_Candidate struct {
	Candidate *ICECandidate `protobuf:"bytes,4,opt,name=candidate,proto3,oneof"` // Кандидат для установки NAT-пробивания
}

type SignalingMessage_Hangup struct {
	Hangup *CallHangup `protobuf:"bytes,5,opt,name=hangup,proto3,oneof"` // Завершение звонка
}

type SignalingMessage_Negotiation struct {
	Negotiation *CallNegotiation `protobuf:"bytes,6,opt,name=negotiation,proto3,oneof"` // Для пересогласования (вкл/выкл видео)
}

func (*SignalingMessage_Offer) isSignalingMessage_Payload() {}

func (*SignalingMessage_Answer) isSignalingMessage_Payload() {}

func (*SignalingMessage_Candidate) isSignalingMessage_Payload() {}

func (*SignalingMessage_Hangup) isSignalingMessage_Payload() {}

func (*SignalingMessage_Negotiation) isSignalingMessage_Payload() {}

// CallOffer содержит SDP (Session Description Protocol) "предложение".
// Это текстовое описание того, какие медиа-потоки (аудио, видео)
// и с какими кодеками хочет отправить инициатор.
type CallOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallOffer) Reset() {
	*x = CallOffer{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallOffer) ProtoMessage() {}

func (x *CallOffer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallOffer.ProtoReflect.Descriptor instead.
func (*CallOffer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *CallOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// CallAnswer содержит SDP "ответ".
// Получатель анализирует Offer и генерирует свой SDP, где указывает,
// какие потоки и кодеки он готов принять.
type CallAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAnswer) Reset() {
	*x = CallAnswer{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAnswer) ProtoMessage() {}

func (x *CallAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAnswer.ProtoReflect.Descriptor instead.
func (*CallAnswer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *CallAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

// ICECandidate содержит информацию, необходимую для установки прямого
// соединения (hole punching) для медиа-трафика.
// Клиенты обмениваются несколькими такими сообщениями.
type ICECandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateJson string                 `protobuf:"bytes,1,opt,name=candidate_json,json=candidateJson,proto3" json:"candidate_json,omitempty"` // ICE-кандидат, обычно в формате JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *ICECandidate) GetCandidateJson() string {
	if x != nil {
		return x.CandidateJson
	}
	return ""
}

// CallHangup - простое сообщение для завершения звонка.
type CallHangup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "занято", "отклонено", "завершено"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallHangup) Reset() {
	*x = CallHangup{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallHangup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallHangup) ProtoMessage() {}

func (x *CallHangup) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallHangup.ProtoReflect.Descriptor instead.
func (*CallHangup) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *CallHangup) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CallNegotiation используется для изменения параметров звонка "на лету"
// (например, включение видео или демонстрации экрана).
// По сути, это просто новый Offer.
type CallNegotiation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallNegotiation) Reset() {
	*x = CallNegotiation{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallNegotiation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallNegotiation) ProtoMessage() {}

func (x *CallNegotiation) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallNegotiation.ProtoReflect.Descriptor instead.
func (*CallNegotiation) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *CallNegotiation) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\bprotocol\"\xba\x02\n" +
	"\x10SignalingMessage\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12+\n" +
	"\x05offer\x18\x02 \x01(\v2\x13.protocol.CallOfferH\x00R\x05offer\x12.\n" +
	"\x06answer\x18\x03 \x01(\v2\x14.protocol.CallAnswerH\x00R\x06answer\x126\n" +
	"\tcandidate\x18\x04 \x01(\v2\x16.protocol.ICECandidateH\x00R\tcandidate\x12.\n" +
	"\x06hangup\x18\x05 \x01(\v2\x14.protocol.CallHangupH\x00R\x06hangup\x12=\n" +
	"\vnegotiation\x18\x06 \x01(\v2\x19.protocol.CallNegotiationH\x00R\vnegotiationB\t\n" +
	"\apayload\"\x1d\n" +
	"\tCallOffer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\"\x1e\n" +
	"\n" +
	"CallAnswer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\"5\n" +
	"\fICECandidate\x12%\n" +
	"\x0ecandidate_json\x18\x01 \x01(\tR\rcandidateJson\"$\n" +
	"\n" +
	"CallHangup\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"#\n" +
	"\x0fCallNegotiation\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdpB\x04Z\x02./b\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_signaling_proto_goTypes = []any{
	(*SignalingMessage)(nil), // 0: protocol.SignalingMessage
	(*CallOffer)(nil),        // 1: protocol.CallOffer
	(*CallAnswer)(nil),       // 2: protocol.CallAnswer
	(*ICECandidate)(nil),     // 3: protocol.ICECandidate
	(*CallHangup)(nil),       // 4: protocol.CallHangup
	(*CallNegotiation)(nil),  // 5: protocol.CallNegotiation
}
var file_signaling_proto_depIdxs = []int32{
	1, // 0: protocol.SignalingMessage.offer:type_name -> protocol.CallOffer
	2, // 1: protocol.SignalingMessage.answer:type_name -> protocol.CallAnswer
	3, // 2: protocol.SignalingMessage.candidate:type_name -> protocol.ICECandidate
	4, // 3: protocol.SignalingMessage.hangup:type_name -> protocol.CallHangup
	5, // 4: protocol.SignalingMessage.negotiation:type_name -> protocol.CallNegotiation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	file_signaling_proto_msgTypes[0].OneofWrappers = []any{
		(*SignalingMessage_Offer)(nil),
		(*SignalingMessage_Answer)(nil),
		(*SignalingMessage_Candidate)(nil),
		(*SignalingMessage_Hangup)(nil),
		(*SignalingMessage_Negotiation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
